// <auto-generated />
using System;
using Drive.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drive.Data.Migrations
{
    [DbContext(typeof(DriveDbContext))]
    [Migration("20241226170622_FixedSeed")]
    partial class FixedSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drive.Data.Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("FileId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "What is this!?",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 909, DateTimeKind.Utc).AddTicks(243),
                            FileId = 1,
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 909, DateTimeKind.Utc).AddTicks(598)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Content = "That is related doc.",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 909, DateTimeKind.Utc).AddTicks(1014),
                            FileId = 1,
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 909, DateTimeKind.Utc).AddTicks(1015)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            Content = "Ughhh, this is boring!",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 909, DateTimeKind.Utc).AddTicks(1018),
                            FileId = 15,
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 909, DateTimeKind.Utc).AddTicks(1019)
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "A general document related content.",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(3515),
                            FolderId = 1,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(3879),
                            Name = "RelatedDoc.txt",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "A quote from a business strategy book: 'The only limit to our realization of tomorrow is our doubts of today.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4217),
                            FolderId = 2,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4218),
                            Name = "BusinessDoc",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Invoices and bills for various expenses can be found here.",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4222),
                            FolderId = 3,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4223),
                            Name = "Invoice.pdf",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "An outline for a presentation on business development.",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4226),
                            FolderId = 4,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4227),
                            Name = "PresentationIdeas.txt",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Project planning notes for a new software development project.",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4230),
                            FolderId = 5,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4246),
                            Name = "ProjectPlanning.txt",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Code snippets and documentation for the Python web scraper.",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4254),
                            FolderId = 6,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4255),
                            Name = "PythonLibDoc.txt",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "An eBook excerpt: 'The future belongs to those who believe in the beauty of their dreams.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4258),
                            FolderId = 8,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4259),
                            Name = "Quotes.txt",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 8,
                            Content = "A song lyric: 'Music can change the world because it can change people.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4262),
                            FolderId = 9,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4263),
                            Name = "Lyrics.txt",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 9,
                            Content = "Book review: 'A journey of a thousand pages begins with a single chapter.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4267),
                            FolderId = 10,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4268),
                            Name = "Reviews.txt",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 11,
                            Content = "A quote from a classic novel: 'To be, or not to be, that is the question.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4273),
                            FolderId = 10,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4274),
                            Name = "NovelQuote.txt",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 12,
                            Content = "An excerpt from a bestselling book: 'The only thing we have to fear is fear itself.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4277),
                            FolderId = 10,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4278),
                            Name = "Books.txt",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 13,
                            Content = "A passage from a famous literary work: 'It was the best of times, it was the worst of times.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4281),
                            FolderId = 10,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4282),
                            Name = "FamousWork.txt",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 14,
                            Content = "A snippet from a popular novel: 'In the end, we only regret the chances we didn't take.'",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4285),
                            FolderId = 10,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4286),
                            Name = "Novels.txt",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 15,
                            Content = "a2 – b2 = (a – b)(a + b)",
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4289),
                            FolderId = 7,
                            LastModifiedAt = new DateTime(2024, 12, 26, 17, 6, 21, 908, DateTimeKind.Utc).AddTicks(4290),
                            Name = "ScriptForMaths.txt",
                            OwnerId = 4
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 905, DateTimeKind.Utc).AddTicks(6672),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 905, DateTimeKind.Utc).AddTicks(6829),
                            Name = "Root",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8905),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8911),
                            Name = "Business Documents",
                            OwnerId = 1,
                            ParentFolderId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8916),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8917),
                            Name = "Bills",
                            OwnerId = 1,
                            ParentFolderId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8920),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8921),
                            Name = "Root",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8924),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8925),
                            Name = "Root",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8945),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8946),
                            Name = "Python Web Scraper",
                            OwnerId = 3,
                            ParentFolderId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8949),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8950),
                            Name = "Root",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8953),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8954),
                            Name = "eBook",
                            OwnerId = 4,
                            ParentFolderId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8957),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(8958),
                            Name = "Root",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(9546),
                            LastModified = new DateTime(2024, 12, 26, 17, 6, 21, 907, DateTimeKind.Utc).AddTicks(9548),
                            Name = "Root",
                            OwnerId = 6
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Share", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("SharedById")
                        .HasColumnType("integer");

                    b.Property<int>("SharedWithId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SharedById");

                    b.HasIndex("SharedWithId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            ItemType = 1,
                            SharedById = 1,
                            SharedWithId = 2
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 10,
                            ItemType = 0,
                            SharedById = 6,
                            SharedWithId = 3
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan.horvat@gmail.com",
                            Name = "Ivan",
                            PasswordHash = "$2a$11$/UtF5wvKqJBQb.J5RdQNH.I5qdIYZv8hiYPaGe2WsPciA7cb7EHeO",
                            Surname = "Horvat"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ana.petrovic@gmail.com",
                            Name = "Ana",
                            PasswordHash = "$2a$11$3PtEabqUk0JI0hZ.PNhTp.hG3yzHejePXvsJAxbrorEmZnwDm6iYu",
                            Surname = "Petrović"
                        },
                        new
                        {
                            Id = 3,
                            Email = "marko.kovac@gmail.com",
                            Name = "Marko",
                            PasswordHash = "$2a$11$LP4evcnZYgqhxcrdA4ALkeXS1f/Lq8B3hqh95hnkrVuJT5mgrs/0y",
                            Surname = "Kovač"
                        },
                        new
                        {
                            Id = 4,
                            Email = "martina.matic@gmail.com",
                            Name = "Martina",
                            PasswordHash = "$2a$11$GCcT8cPJtULIzDy2wDC7/ul6QmWfUunDlb10.bKY7btJQw4CGjpYm",
                            Surname = "Matić"
                        },
                        new
                        {
                            Id = 5,
                            Email = "luka.simic@gmail.com",
                            Name = "Luka",
                            PasswordHash = "$2a$11$C1sYpFPMUinyDACBKqfpeOB3wm.Ldx3ufIy4KzjIZbhsh/IWOtgWG",
                            Surname = "Šimić"
                        },
                        new
                        {
                            Id = 6,
                            Email = "sara.luksic@gmail.com",
                            Name = "Sara",
                            PasswordHash = "$2a$11$1hLjfmuGoEcrM/843pnfuOX0pPi..u05S/quoDo5nNSjwTH0dlzBm",
                            Surname = "Lukšić"
                        },
                        new
                        {
                            Id = 7,
                            Email = "petar.juric@gmail.com",
                            Name = "Petar",
                            PasswordHash = "$2a$11$LCb9/2SYWrNIdLDHjolcCuFZ5F4r.1J0OuKyjkzwXfllhx8j2LSVG",
                            Surname = "Jurić"
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Comment", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.File", "File")
                        .WithMany("Comments")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.File", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.User", "Owner")
                        .WithMany("Files")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.User", "Owner")
                        .WithMany("Folders")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Share", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.User", "SharedBy")
                        .WithMany()
                        .HasForeignKey("SharedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.User", "SharedWith")
                        .WithMany()
                        .HasForeignKey("SharedWithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.User", null)
                        .WithMany("SharedItems")
                        .HasForeignKey("UserId");

                    b.Navigation("SharedBy");

                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.File", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.User", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Folders");

                    b.Navigation("SharedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
